# Generated by Django 5.2.9 on 2025-12-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('stock', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('BOOKS', 'Books'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing')], default='', max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
